defaults:
  - _self_
  - launcher: local
  - data: pusht

run_name: ${hydra:job.id}

num_workers: 6
train_split: 0.9
seed: 3072
img_size: 224
patch_size: 14
encoder_scale: tiny
embed_dim: 192
encoder_resnet9: False
train_value_function: False
projector_loss_weight: 1e-3
dump_object: True

trainer:
  max_epochs: 100
  devices: auto
  accelerator: gpu
  precision: bf16
  gradient_clip_val: 1.0

loader:
  batch_size: 128
  num_workers: ${num_workers}
  drop_last: True
  persistent_workers: True
  prefetch_factor: 3
  pin_memory: True
  shuffle: True

optimizer:
  type: AdamW
  lr: 5e-5
  weight_decay: 1e-3

wm:
  history_size: 3
  num_preds: 1

model:
  _target_: stable_worldmodel.wm.lewm.LeWM
  encoder:
    _target_: stable_pretraining.backbone.utils.vit_hf
    size: ${encoder_scale}
    patch_size: ${patch_size}
    image_size: ${img_size}
    pretrained: false
    use_mask_token: false
  predictor:
    _target_: stable_worldmodel.wm.lewm.module.Predictor
    num_frames: ${wm.history_size}
    input_dim: ${embed_dim}
    hidden_dim: ${embed_dim}
    output_dim: ${embed_dim}
    depth: 6
    heads: 16
    mlp_dim: 2048
    dim_head: 64
    dropout: 0.1
    emb_dropout: 0.0
  action_encoder:
    _target_: stable_worldmodel.wm.lewm.module.Embedder
    input_dim: ???
    emb_dim: ${embed_dim}
  projector:
    _target_: stable_worldmodel.wm.lewm.module.MLP
    input_dim: ${embed_dim}
    output_dim: ${embed_dim}
    hidden_dim: 2048
    norm_fn:
      _target_: torch.nn.BatchNorm1d
      _partial_: true
  pred_proj:
    _target_: stable_worldmodel.wm.lewm.module.MLP
    input_dim: ${embed_dim}
    output_dim: ${embed_dim}
    hidden_dim: 2048
    norm_fn:
      _target_: torch.nn.BatchNorm1d
      _partial_: true

loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
